import type { NextPage } from "next";
import Head from "next/head";

import Order from "../components/Order";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Order component</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon-32x32.png" />
      </Head>

      <main className="container mx-auto flex h-screen flex-row items-center justify-center">
        <Order />
      </main>
    </div>
  );
};

export default Home;
